//Protected Route
export const FOURTH_COMPONENT = "FOURTH_COMPONENT";
export const FOURTH_REDIRECT = "FOURTH_REDIRECT";
export const TRIPLE_COMPONENT = "TRIPLE_REDIRECT";
export const TRIPLE_REDIRECT = "TRIPLE_REDIRECT";
export const DOUBLE = "DOUBLE";
